spring:
  application:
    name: feign

server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetries: 1 
  MaxAutoRetriesNextServer: 2

item-service:
  ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetries: 1 
  MaxAutoRetriesNextServer: 2
 
feign:
  hystrix:
    enabled: true
    
hystrix:
 command:
       default:
         execution:
           isolation:
             thread:
               timeoutInMilliseconds: 500
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        